version: "2.4"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.18.0
    restart: always
    labels:
      "autoheal": "true"
    healthcheck:
      test: [ "CMD", "echo", "-n", ">", "/dev/tcp/127.0.0.1/8080" ]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      broker:
        condition: service_healthy
    volumes:    
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    privileged: true
    environment:
      - TZ=Europe/London
    ports:
      - "80:8080"
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '2'
  broker:
    container_name: broker
    image: eclipse-mosquitto:latest
    restart: always
    labels:
      "autoheal": "true"
    healthcheck:
      test: [ "CMD", "echo", "-n", ">", "/dev/tcp/127.0.0.1/1883" ]
      interval: 30s
      timeout: 10s
      retries: 10    
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - 9001

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: on-failure
    depends_on:
      - broker
      - zigbee2mqtt
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30
