# vim: tabstop=2 shiftwidth=2 expandtab softtabstop=2 
version: "2.4"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.17.0
    restart: always
    healthcheck:
      test: [ "CMD", "echo", "-n", ">", "/dev/tcp/127.0.0.1/8080" ]
      interval: 180s
      timeout: 10s
      retries: 30
    depends_on:
      mqtt:
        condition: service_healthy
    volumes:    
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/London
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    healthcheck:
      test: [ "CMD", "echo", "-n", ">", "/dev/tcp/127.0.0.1/1883" ]
      interval: 15s
      timeout: 3s
      retries: 10    
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

#  version: '3'
#  services:
#    zigbee2mqtt:
#      container_name: zigbee2mqtt
#      image:version: "2.4"
#        - ./data:/app/data
#        - /run/udev:/run/udev:ro
#      devices:
#        - /dev/ttyUSB0:/dev/ttyACM0
#      restart: always
#      network_mode: host
#      privileged: true
#      environment:
#        - TZ=Europe/London
