version: "2.4"
services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.17.0
    hostname: zigbee2mqtt
    restart: always
    labels:
      "autoheal": "true"
    healthcheck:
      test: [ "CMD", "echo", "-n", ">", "/dev/tcp/127.0.0.1/8080" ]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      mqtt:
        condition: service_healthy
    volumes:    
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/London
  mqtt:
    container_name: mqtt
    hostname: mqtt
    image: eclipse-mosquitto:latest
    restart: always
    labels:
      "autoheal": "true"
    healthcheck:
      test: [ "CMD", "echo", "-n", ">", "/dev/tcp/127.0.0.1/1883" ]
      interval: 30s
      timeout: 10s
      retries: 10    
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    hostname: autoheal
    depends_on:
      mqtt:
        condition: service_healthy
      zigbee2mqtt:
        condition: service_healthy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_INTERVAL=10
      - CURL_TIMEOUT=30
